const routes = [
  {
    api: "/video",
    method: "get",
    microservice: "video provider",
    isAuthenticated: false,
    url: "http://localhost:3002",
  },
  {
    api: "/video/play/:id",
    method: "get",
    microservice: "video provider",
    isAuthenticated: true,
    url: "http://localhost:3002",
  },
  {
    api: "/video/rating/:id",
    method: "put",
    microservice: "video provider",
    isAuthenticated: true,
    url: "http://localhost:3002",
  },
  {
    api: "/comment",
    method: "post",
    microservice: "video provider",
    isAuthenticated: true,
    url: "http://localhost:3002",
  },
  {
    api: "/comment/:id",
    method: "put",
    microservice: "video provider",
    isAuthenticated: true,
    url: "http://localhost:3002",
  },
  {
    api: "/comment/reply/:id",
    method: "put",
    microservice: "video provider",
    isAuthenticated: true,
    url: "http://localhost:3002",
  },
  {
    api: "/comment",
    method: "get",
    microservice: "video provider",
    isAuthenticated: true,
    url: "http://localhost:3002",
  },
  {
    api: "/user/signup",
    method: "post",
    microservice: "IDP",
    isAuthenticated: false,
    url: "http://localhost:3001",
  },
  {
    api: "/user/login",
    method: "post",
    microservice: "IDP",
    isAuthenticated: false,
    url: "http://localhost:3001",
  },
  {
    api: "/user/profile",
    method: "get",
    microservice: "IDP",
    isAuthenticated: true,
    url: "http://localhost:3001",
  },
  {
    api: "/user/profile",
    method: "put",
    microservice: "IDP",
    isAuthenticated: true,
    url: "http://localhost:3001",
  },
];
module.exports = routes;
